app_test/urls.py
from django.conf.urls import include, url
from app_test import views
app_name = 'app_test'

urlpatterns = [
    url(r'^$', views.AssetView.as_view(), name='index'),
    url(r'^asset/(?P<pk>[0-9]+)/well/$', views.well_func, name='detail'),
    url(r'^asset/(?P<pk>[0-9]+)/layer/$', views.layer_func, name='detail2'),
    url(r'^intersection/(?P<id>[0-9]+)/$', views.intersection_func, name='detail_inter'),
]

sofoil/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('app_test.urls')),
]

app_test/models.py
from django.db import models

# Create your models here.

class Asset(models.Model):
    class Meta():
        verbose_name = 'Месторождение'
        verbose_name_plural = 'Месторождения'

    name = models.CharField('Наименование', max_length=200)

    def __str__(self):
        return self.name


class Layer(models.Model):
    class Meta():
        verbose_name = 'Пласт'
        verbose_name_plural = 'Пласты'

    name = models.CharField('Наименование', max_length=200)
    asset = models.ForeignKey(Asset, blank=True, null=True,
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Well(models.Model):
    class Meta():
        verbose_name = 'Скважина'
        verbose_name_plural = 'Скважины'

    name = models.CharField('Наименование', max_length=200)
    X = models.FloatField('X', blank=False, null=False)
    Y = models.FloatField('Y', blank=False, null=False)
    asset = models.ForeignKey(Asset, blank=True, null=True,
                             on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Intersection(models.Model):
    class Meta():
        verbose_name = 'Пластопересечение'
        verbose_name_plural = 'Пластопересечения'

    X = models.FloatField('X', blank=False, null=False)
    Y = models.FloatField('Y', blank=False, null=False)
    well = models.ForeignKey(Well, blank=True, null=True,
                             on_delete=models.CASCADE)

    layer = models.ForeignKey(Layer, blank=True, null=True,
                             on_delete=models.CASCADE)

app_test/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse
from django.views import generic
from app_test.models import Well, Intersection, Layer, Asset


# Create your views here.

class AssetView(generic.ListView):
    template_name = 'sofoil/index.html'
    context_object_name = 'asset_list'

    def get_queryset(self):
        return Asset.objects.all()


def well_func(request, pk):
    well_list = Well.objects.filter(asset=pk)
    return render(request, 'sofoil/detail.html', {'well_list': well_list})


def layer_func(request, pk):
    layer_list = Layer.objects.filter(asset=pk)
    return render(request, 'sofoil/detail2.html', {'layer_list': layer_list})


def intersection_func(request, id):
    inter_list = Intersection.objects.filter(well=id)
    return render(request, 'sofoil/results.html', {'inter_list': inter_list})

app_test/templates/sofoil/detail.html
{% extends 'sofoil/index.html' %}
{% block title %} {{ block.main }} Список скважин {% endblock %}
{% block content %}

<table class="table table-bordered table-dark">
    <thead>
    <tr>
        <td>Наименование</td>
        <td>X</td>
        <td>Y</td>
    </tr>
    </thead>
    <tbody>
    {% for t in well_list %}
    <tr>
        <td><a href="{% url 'app_test:detail_inter' t.id %}">{{ t.name }}</a></td>
        <td>{{ t.X }}</td>
        <td>{{ t.Y }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{% url 'app_test:index' %}">назад</a>
{% endblock %}

app_test/templates/sofoil/detail2.html
{% extends 'sofoil/index.html' %}
{% block title %} {{ block.main }} Список скважин {% endblock %}
{% block content %}

<table class="table table-bordered table-dark">
    <thead>
    <tr>
        <td>Наименование</td>
        <td>Месторождение</td>
    </tr>
    </thead>
    <tbody>
    {% for t in layer_list %}
    <tr>
        <td>{{ t.name }}</td>
        <td>{{ t.asset.name }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{% url 'app_test:index' %}">назад</a>
{% endblock %}

app_test/templates/sofoil/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Кандидаты - {% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
<ul class="list-group">
    {% for asset in asset_list %}
        <li class="list-group-item"><a href="{% url 'app_test:index' %}">Начальная страница</a></li>
        <li class="list-group-item"><a href="{% url 'app_test:detail' asset.id %}">Список скважин</a></li>
        <li class="list-group-item"><a href="{% url 'app_test:detail2' asset.id %}">Список пластов</a></li>
    {% endfor %}
</ul>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% block content %}{% endblock %}
</body>
</html>

app_test/templates/sofoil/results.html
{% extends 'sofoil/index.html' %}
{% block title %} {{ block.main }} Список Пластопересечений {% endblock %}
{% block content %}

<table class="table table-bordered table-dark">
    <thead>
    <tr>
        <td>Наименование скважин</td>
        <td>Наименование пластов</td>
        <td>X</td>
        <td>Y</td>
    </tr>
    </thead>
    <tbody>
    {% for t in inter_list %}
    <tr>
        <td>{{ t.well.name }}</td>
        <td>{{ t.layer.name }}</td>
        <td>{{ t.X }}</td>
        <td>{{ t.Y }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
    <a href="{% url 'app_test:index' %}">назад</a>
{% endblock %}